[build]
builder = "nixpacks"
buildCommand = "apt-get update && apt-get install -y yt-dlp && npm install"

[deploy]
startCommand = "npm start"
healthcheckPath = "/"
healthcheckTimeout = 100
restartPolicyType = "on_failure"
restartPolicyMaxRetries = 3

[deploy.env]
NODE_ENV = "production" 