[build]
builder = "nixpacks"
buildCommand = "npm install && pip3 install --no-cache-dir --upgrade yt-dlp"

[deploy]
startCommand = "npm start"
healthcheckPath = "/"
healthcheckTimeout = 100
restartPolicyType = "on_failure"
restartPolicyMaxRetries = 3

[deploy.env]
NODE_ENV = "production" 